### ISSUE TITLE
Dead links under "Features" section

### ISSUE THREAD

**Issue by Jxlle** [ML-KULeuven/dtaianomaly#53]
All urls attached to the "Learn more" clickable links don't work.

**Comment by LouisCarpentier42** [comment]
Thanks for noticing the issue! The documentation has indeed changed, in which all the features were grouped together in a separate tab within the documentation. In general, the URL should be changed form ``.../getting_started/<feature-name>.html`` to ``.../getting_started/examples/<feature-name>.html``. Would you be able to do this? This should be the correct text: 

> The three key features of `dtaianomaly` are as follows:
> 1. State-of-the-art time series anomaly detection via a simple API. [Learn more!](https://dtaianomaly.readthedocs.io/en/stable/getting_started/examples/anomaly_detection.html)
> 2. Develop custom models for anomaly detection. [Learn more!](https://dtaianomaly.readthedocs.io/en/stable/getting_started/examples/custom_models.html)
> 3. Quantitative evaluation of time series anomaly detection. [Learn more!](https://dtaianomaly.readthedocs.io/en/stable/getting_started/examples/quantitative_evaluation.html)

I also noticed another URL in the documentation is wrong (but still referencing to a valid page). The last url in the ``Example`` documentation points to the home of the documentation, but this should be pointing to the ``Examples`` page in the documentation. The correct URL is ``https://dtaianomaly.readthedocs.io/en/stable/getting_started/examples.html``. Can you update this as well?
